name: credit server

on:
  push:
    branches: [ main ]
    paths: 
      - 'credit-server/**'
      - '!credit-server/**/README.md'
      - '!credit-server/**/**.dockerignore'
      - '!credit-server/**/tsconfig.json'
  pull_request:
    branches: [ main ]
    paths: 
      - 'credit-server/**'
      - '!credit-server/**/README.md'
      - '!credit-server/**/**.dockerignore'
      - '!credit-server/**/tsconfig.json'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./credit-server

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: credit-server/package-lock.json
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npm test
