name: credit server

on:
  push:
    branches: [ main ]
    paths: 
      - 'credit-server/**'
      - '!credit-server/**/README.md'
      - '!credit-server/**/**.dockerignore'
      - '!credit-server/**/tsconfig.json'
  pull_request:
    branches: [ main ]
    paths: 
      - 'credit-server/**'
      - '!credit-server/**/README.md'
      - '!credit-server/**/**.dockerignore'
      - '!credit-server/**/tsconfig.json'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./credit-server

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
