name: credit client

on:
  push:
    branches: [ main ]
    paths: 
      - 'credit-client/**'
      - '!credit-client/**/README.md'
      - '!credit-client/**/public/**'
  pull_request:
    branches: [ main ]
    paths: 
     - 'credit-client/**'
     - '!credit-client/**/README.md'
     - '!credit-client/**/public/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./credit-client

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: credit-client/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test -- --watchAll=false
